import './globals.css'
import CrisisSupport from './components/CrisisSupport'

export const metadata = {
  title: 'Lily',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <CrisisSupport />
      </body>
    </html>
  )
}
